### ISSUE TITLE
Lovelace Gauge Card rendering not correct when in horizontal Stack

### ISSUE THREAD

**Issue by mchinery** [MCrissDev/Ariela#1]
I have two gauge cards in the horizontal stack and they do not render correctly. See screenshot
![screenshot_20190206-144933](https://user-images.githubusercontent.com/1004690/52350672-fe94de80-2a20-11e9-8971-9efb4e4686ca.jpg)

**Comment by MCrissDev** [comment]
Thank you. I will fix this issue on the next release.

**Comment by MCrissDev** [comment]
Fixed in version 1.2.8.3
