### ISSUE TITLE
Device name keeps getting reset

### ISSUE THREAD

**Issue by cliffordwhansen** [MCrissDev/Ariela#118]
I have noticed that some of my sensors stop reporting, and upon investigation I find that the "Device Name" setting gets reset.

Settings > Common > Device Name: clifford_ariela

I'm not 100% sure, but it seems change when I change networks (Wifi -> 3G -> Work wifi) and normally gets changed to: android_lge_joan_8.0.0 (not sure where that name comes from)

There was even once when it got changed to: NiGhTHawKV30 (which looks like the Bluetooth Name)

This is happening in both the free and paid for versions.

**Comment by MCrissDev** [comment]
Hello,
Can you share some logs so i can check it out? Thank you

**Comment by cliffordwhansen** [comment]
@MCrissDev I have enabled debug mode, and when it happens again I will upload the logs. The good news is I have not seen it happen again, which is both weird and nice ;)

I will close this for now, and reopen it later if this happens again.

**Comment by MCrissDev** [comment]
Great, please let me know if this happens again :D
