### ISSUE TITLE
Background location permission for android Q

### ISSUE THREAD

**Issue by gmusa** [MCrissDev/Ariela#147]
Background location reporting is not working in Android Q, 

Only showing _"deny"_ and _"Allow only while the app is in use"_ permission are shown the missing option is _"Allow all the time"_

https://medium.com/google-developer-experts/exploring-android-q-location-permissions-64d312b0e2e1

**Comment by MCrissDev** [comment]
Hello,
This issue has been fixed in 1.3.6.9
Please let me know if you encounter any issues with it
