### ISSUE TITLE
Sensors state update sending frequency/battery power drain

### ISSUE THREAD

**Issue by Elkropac** [MCrissDev/Ariela#155]
Hello,
can you please implement some setting to limit, when to send sensor state updates?
Recently (after app upgrade or after changing sensors from mqtt to mobile-app?),  I have problems with battery life. 
I leave home at 7AM with 98-100% battery and I come back at 7PM with <10% of battery. 
Before that change, it was around 30% of battery left .
I found out, that when i turn off pressure, proximity and lux sensors, my battery life is back.

It would be great if user can set (per sensor), how often to send sensors states.
Options should be:
 - "Send on change"  (today behaviour? - good for screen state)
 - "Send every 'time unit'". 

There also should be secondary option "send only if new state value is more than x % from last sent state"

**Comment by MCrissDev** [comment]
Hello,
Now the updates are send every 10 seconds. I will see what i can do to add some settings regarding this.

**Comment by Elkropac** [comment]
Hi,
is this change in Ariela pro version 1.3.7.2 ?
If so, I will test tomorrow. (by enabling those frequently updating sensors)

BTW: is it possilble, that sending data over mobile app is more power hungry then sending data over MQTT?

Thanks

**Comment by MCrissDev** [comment]
Hello,
I didn't added the settings in the new version.
You could try switching to mqtt and see what is the result. In theory mobile_app should be less battery intensive

**Comment by MCrissDev** [comment]
Please check the 1.4.0 version of the app. Battery consumption should be drastically improved.
