### ISSUE TITLE
Support for Client Certificate authentication

### ISSUE THREAD

**Issue by photinus** [MCrissDev/Ariela#16]
Please consider adding support for Client Certificate authentication when connecting to Home assistant through a NGINX proxy or other such proxy.

**Comment by MCrissDev** [comment]
I will investigate and it will be fixed soon

**Comment by photinus** [comment]
Thanks, If you need a server to test against, let me know and I can spin one up and provide a client cert for authenticating against it.

**Comment by MCrissDev** [comment]
Thank you very much. Whenever you can provide such details i can start investigating this.

**Comment by MCrissDev** [comment]
Hello,
Can you send me a server link so i can test against?
Thank you.

**Comment by photinus** [comment]
What's the best way for me to securely email you a client cert for testing?

**Comment by MCrissDev** [comment]
Use the contact option from Ariela to send me an email with the details. Thank you.

**Comment by photinus** [comment]
Sent.
~Will

**Comment by MCrissDev** [comment]
Fixed in version 1.3.1.5
