### ISSUE TITLE
Horizontal - vertical stack

### ISSUE THREAD

**Issue by INTELBB** [MCrissDev/Ariela#17]
Is it possible to add horizontal stack to Ariela?
I'm using it to organize entity-button card's.

**Comment by MCrissDev** [comment]
Horizontal stack is already implemented, but because some users do not know that they will have to scroll to see other items, the horizontal stack will behave like a horizontal one. I will add an option that will allow changing this behavior.

**Comment by MCrissDev** [comment]
Added a new option in Ariela -> Settings -UI that will make horizontal stack behave or not as vertical cards. Version : 1.3.0.5
