### ISSUE TITLE
hue card: selector broken in ariela pro

### ISSUE THREAD

**Issue by xchwarze** [MCrissDev/Ariela#174]
![Screenshot_20191205-002220_Ariela](https://user-images.githubusercontent.com/2120205/70840762-56476780-1df3-11ea-9400-a1a21debaed0.jpg)

The first option is not selectable

**Comment by MCrissDev** [comment]
You mean the current effect? If for example color loop is your current effect then you can change to random in your case. Does that makes any sense?

**Comment by xchwarze** [comment]
There is no effect selected, it just looks like this.
Nor does he let me select the colorloop effect because he thinks I have it selected.
This defect was not present a few months ago.

**Comment by MCrissDev** [comment]
Ok, i think i understand now. Then possible that HA reported that the colorloop was the active one?
Can you enabled debug mode in Ariela so i can check it out? (do not forget to reproduce the problem first).

**Comment by MCrissDev** [comment]
Hello,

This issue should be fixed in Ariela 1.4.3
