### ISSUE TITLE
hue card: missing color wheel in tablet

### ISSUE THREAD

**Issue by xchwarze** [MCrissDev/Ariela#175]
The color wheel does not appear when the app is used on a tablet.
Sorry for how this issue was created but doing it from the tablet was a real PITA

**Comment by xchwarze** [comment]
![Screenshot_20191213-210219_Ariela](https://user-images.githubusercontent.com/2120205/70840883-7297d400-1df4-11ea-9a2f-5e7f9586fc38.jpg)
![Screenshot_20191213-210224_Ariela](https://user-images.githubusercontent.com/2120205/70840893-88a59480-1df4-11ea-828b-0d4dc1a4d2e9.jpg)

**Comment by MCrissDev** [comment]
That's strange. Can you tell me tablet Android version?

**Comment by xchwarze** [comment]
Android 9

**Comment by MCrissDev** [comment]
Thank you. I will check it out on a emulator since i do not have any available devices. I will retrune with the results i have.

**Comment by MCrissDev** [comment]
Hello,

This issue should be fixed in Ariela 1.4.3
