### ISSUE TITLE
[Feature Request] Report Connected Bluetooth device Battery Levels and Locations

### ISSUE THREAD

**Issue by kevjs1982** [MCrissDev/Ariela#18]
It would be really useful to make use of the battery level connected Bluetooth devices into Home Assistant from within Ariela

I've documented how I got part of it working with Tasker/PHP/REST here https://community.home-assistant.io/t/remember-to-charge-your-bluetooth-headset-requires-tasker-on-android/52118 but this is a bit on the messy side.

For each device found, it you'd probably want to have it keyed off the MAC address - so that if a device is paired with multiple phones it would have a single MQTT topic(s).  As I write this down it seems that this would be best implemented as a Device Tracker Component.

The useful attributes would be:-
* state: active / inactive
* last_connected_to: Kev's Pixel 2  _Would show the last connected too device_
* last_seen: 2019-03-01 01:01:01
* latitude: 52.06972
* longitude: -1.02144
* location_updated: 2019-03-01 00:02:01
* battery_level: 60%
* battery_level_updated: 2019-03-01 00:02:01
* mac_address
* description

The location would be updated on connect, disconnect, and at any time the location provider within Ariela reports an update.  Not all devices report their battery level, however location would still be useful

**Use Cases**

- Where did I park my car? (Use the latitude/longitude of the Bluetooth Stereo)
- What headsets do I need to charge?
- Remind me to charge my headsets?
- I can't find my headphones, where did I last use them?
- I can't find the bathroom speaker, who used it last?

**Comment by MCrissDev** [comment]
Thank you very much for the suggestion. I will have to think on a method to pack all these things.

**Comment by MCrissDev** [comment]
Hello,
Version 1.3.0.6 introduce new HFP / A2DP Bluetooth sensors. These sensors will give you fallowing details:
- last_device_name = last device name connected
- last_device_mac = last device mac
- icon 
- last_device_latitude = last latitude when the device connected / disconnected
- last_device_longitude = last longitude when the device connected / disconnected
- maps = link that will open in Ariela maps that will show the location of device
- active = true if the device is connected or false if not
- last_seen = last timestamp when the device communicated with your phone

Battery informations are not that easy to retrieve, but in the future i will try to implement that too.
Please let me know if works.
