### ISSUE TITLE
Add unit of measurement to MQTT battery state

### ISSUE THREAD

**Issue by kentloving** [MCrissDev/Ariela#180]
The state of the phone's battery as reported via mitt does not include a "unit_of_measurement" attribute. So HA won't create a line graph in History or on a Lovelace Sensor card.

My workaround is to add this attribute using the HA Customize Entities page.

But I think better solution would have Ariela change to add this attribute. Also add the attribute to other sensors where appropriate.

Thanks for your consideration.

**Comment by MCrissDev** [comment]
Thank you for the suggestion this new info will be added in Ariela version 1.4.4
