### ISSUE TITLE
Alarm sensor showing next calender alert

### ISSUE THREAD

**Issue by rayaar** [MCrissDev/Ariela#186]
As the title say, when I use the alarm sensor I get the next calendar alert as well as the wake up alarm time. I was expecting to only get the wake up alarm time.
I am using a Samsung galaxy s20+ on Ariela 1.3.8.3 on android 10.

**Comment by MCrissDev** [comment]
Hello,

This issue is not something that Ariela can control or be fixed since its what the OS is reporting.
