### ISSUE TITLE
WearOS app doesn't work at all

### ISSUE THREAD

**Issue by Red-M** [MCrissDev/Ariela#187]
I'm trying to simply turn my zigbee lights on and off via the WearOS app and it doesn't do anything.
Areila on my phone can control any on my Home Assistant but my watch cannot do anything at all.

I installed Areila on my WearOS watch via the Play store and I have paid for the pro upgrade as well.

**Comment by MCrissDev** [comment]
Hello,

Please check the latest version of the Ariela. The issue should be fixed.
