### ISSUE TITLE
Lovelace (header) Icons do not show up on old Android Versions.

### ISSUE THREAD

**Issue by thehaxxa** [MCrissDev/Ariela#23]
As witnessed in the screenshot: 

![Screenshot_2019-03-15-23-32-25](https://user-images.githubusercontent.com/2765052/54432271-d36a8100-477c-11e9-964d-cb8730a16641.png)
![Screenshot_2019-03-15-23-32-20](https://user-images.githubusercontent.com/2765052/54432274-d5344480-477c-11e9-9025-fc353eb2c922.png)

The Lovelace (header) icons do not show up on older Android Devices, specifically in this context a Android Tablet (Dell Venue 3840) running Android 4.4 KitKat:  

![Screenshot_2019-03-15-23-33-31](https://user-images.githubusercontent.com/2765052/54432283-dc5b5280-477c-11e9-896b-97f743a5e286.png)
![Screenshot_2019-03-15-23-33-08](https://user-images.githubusercontent.com/2765052/54432291-e0877000-477c-11e9-873f-a4a2480e4ca0.png)

Works fine on all my newer devices. 

Happy to provide more information if required. 
- Thanks

**Comment by MCrissDev** [comment]
Hello,
Please enable debug mode in Ariela and provide the logs so i can investigate.
Thank you

**Comment by thehaxxa** [comment]
[ariela_logfile.log](https://github.com/MCrissDev/Ariela/files/2971127/ariela_logfile.log)

Attached. 

Thanks

**Comment by thehaxxa** [comment]
The issue has been fixed in the latest update.
