### ISSUE TITLE
[Feature Request] FIND3 Emulation

### ISSUE THREAD

**Issue by eifinger** [MCrissDev/Ariela#24]
I am using [FIND3](https://github.com/schollz/find3) to determine room occupancy.
The developer offers a dedicated Android App for that under https://github.com/schollz/find3-android-scanner. The problem is, that everytime this app scans for WIFI it turns on the screen.

I found [Zanzito](https://community.home-assistant.io/t/zanzito-a-lightweight-bridge-between-your-android-device-and-your-mqtt-home-automation-system/20228) which offers FIND3 emulation without the screen turning on.

It would be great if Ariela offers the same feature as Zanzito, thus eliminating the need for one more app.

**Comment by MCrissDev** [comment]
Hello,

Thank you for the suggestion. I will see what i can do about this.
