### ISSUE TITLE
 [BUG] Ariela not starting on phone reboot.

### ISSUE THREAD

**Issue by jazzyisj** [MCrissDev/Ariela#25]
Pixel OG / Android 9 - Ariela 1.3.1.0 does not start up automatically on phone restart

**Comment by MCrissDev** [comment]
Hello,

I did some testing and it seems the Ariela starts after reboot. What it happens is that the boot complete event is send a little earlier, so sometimes can take some time to see Ariela started. Can you confirm that Ariela did not start after 5 minutes let say?

**Comment by jazzyisj** [comment]
OK I finally had some time to fool around and test for you.  If lock screen security is disabled Ariela will start after a few moments as you said.  If the screen is locked on startup Ariela does start once it has been unlocked.  Apparently the wife can go all day without unlocking her phone... was confusing me.  

I reinstalled Owntracks to see if it behaved the same way and it does.  I mistakenly thought it would open in the background w/o having to unlock the phone.  So I'm guess its a limitation of Android.   But Owntracks does actually open in the background, which is nice.

Shouldn't Ariela also start in the background without opening the UI every time?  Forcing the user to have to close it every time the phone restarts or Ariela gets updated (which is a lot! :-) creates an avoidable annoyance IMHO.  These things should happen in the background without being noticed. 

Anyway thanks for clarifying for me.  Still having a couple other issues, will report them in the appropriate threads.   Thanks again!

**Comment by MCrissDev** [comment]
I will see what i can do to start Ariela in the background. Maybe next release will contain this feature.
