### ISSUE TITLE
[Feature request][Low priority] Make sticky sensors smaller when scrolling

### ISSUE THREAD

**Issue by Devqon** [MCrissDev/Ariela#3]
The badges in the UI are sticky, so they always take up some space in the screen. It might be a good idea to make them smaller when the user is scrolling down.

**Comment by MCrissDev** [comment]
I will add this to my TODO list. Thank you for the suggestion

**Comment by MCrissDev** [comment]
Badges can now be scrolled (and hide) starting with version 1.3.2.2
