### ISSUE TITLE
TTS Issue

### ISSUE THREAD

**Issue by MCrissDev** [MCrissDev/Ariela#30]
From HA forum:

topic: homeassistant/tts/android_repsp10_tts/tts
payload_template: Indoor temperature is {{ states.sensor.vana_maja.attributes.Toas }} degrees Celsius.
Text is read out OK but not sensor value. HA debug log shows proper conversion:
2019-03-25 18:50:02 DEBUG (MainThread) [homeassistant.components.mqtt] Transmitting message on homeassistant/tts/android_repsp10_tts/tts: Indoor temperature is 15.9 degrees Celsius. 2019-03-25 18:50:02 DEBUG (MainThread) [homeassistant.components.mqtt] Received message on homeassistant/tts/android_repsp10_tts/tts: b'Indoor temperature is 15.9 degrees Celsius.'
Ariela log shows not converted data:
03-25 18:50:00.936 19645 19828 I TextToSpeech: Set up connection to ComponentInfo{ee.eki.ekisynt/ee.eki.ekisynt.EKISpeakService}
03-25 18:50:00.937 19645 19645 E HA_TTSMqttSensor: TTSMqttSensor: This Language is not supported
03-25 18:50:02.818 19645 19673 D HA_HassWebSocket: onMessage: message = {“event”: {“event_type”: “call_service”, “context”: {“user_id”: “a839ea0f095445aeaff7b722647bb3e4”, “parent_id”: null, “id”: “4fbc58f06f0e4d65aae68b7041a8a1ab”}, “data”: {“domain”: “mqtt”, “service_data”: {“payload_template”: “Indoor temperature is {{ states.sensor.vana_maja.attributes.Toas }} degrees Celsius.”, “topic”: “homeassistant/tts/android_repsp10_tts/tts”}, “service”: “publish”}, “time_fired”: “2019-03-25T16:50:02.861617+00:00”, “origin”: “LOCAL”}, “type”: “event”, “id”: 3}
03-25 18:50:02.819 19645 19673 D HA_MQTTAddon: onMQTTTopicReceived: topic = homeassistant/tts/android_repsp10_tts/tts payload = Indoor temperature is {{ states.sensor.vana_maja.attributes.Toas }} degrees Celsius.

**Comment by Repsionu** [comment]
Thanks for quick reaction on this. It was my stupid head that forgot a HASS postulate: **if it contains data fields/variables it is atemplate** So after replacing in automation: section service: mqtt:publish **data:** to **data_template:** it worked fine. Sorry for my prompt request after only 2 days of testing and googling etc. :-(
Best regards, JR
Guess this issue can be closed and You can focus on Your superb ideas...

**Comment by MCrissDev** [comment]
I am glad to hear the issue was resolved, great job you did in identifying the issue.
Please let me know if you encounter other issues with Ariela.
