### ISSUE TITLE
[Feature Request] Add refresh for web ui

### ISSUE THREAD

**Issue by editter** [MCrissDev/Ariela#34]
The web UI doesn't seem to refresh correctly. I assume it's a cache issue but I can't seem to get it to refresh so I was wondering if a button/pull down gesture could be added to clear cache and reload the web view.

**Comment by jazzyisj** [comment]
@editter Have you tried the refresh command available from the 3 dot menu on the right side of the HA header?  It sometimes takes a few seconds for it to refresh, but it does work.  I do agree that some sort of indicator that the page is in the process of refreshing would be helpful, but that is a Home Assistant issue, not Ariela.

**Comment by editter** [comment]
I don't see that button anymore, I assumed it went away a few versions ago.  I only see "Unused entities", "Configure UI", and "Help"

**Comment by jazzyisj** [comment]
Ah I guess you're not using YAML mode for lovelace.  In storage mode the UI is supposed to refresh automagically.

https://community.home-assistant.io/t/lovelace-refresh-option-in-the-3-dot-menu-not-there/87124

**Comment by editter** [comment]
Interesting, I wasn't aware of that so thanks for pointing it out!

Adding a bit more context to this request.  When the version changes on the desktop I get a little alert asking to "Reload" which re-pulls from the server.  I assume its due to the service worker cache but I have not confirmed that.  In mobile, I just pull down to refresh and it reflects any changes.  In the app, there is no way to do it as far as I can tell.

**Comment by jazzyisj** [comment]
That notice you get is only after the frontend javascript needs to be refreshed after an update I believe.  You should also get it on mobile.  I do get what you're saying about the refresh now though, especially if you don't have access to the yes I agree it could be useful in Ariela.

**Comment by MCrissDev** [comment]
Version 1.3.2.2 added option to scroll down to refresh
