### ISSUE TITLE
Cover buttons are confusing in Dark Theme.

### ISSUE THREAD

**Issue by thehaxxa** [MCrissDev/Ariela#44]
Subtle theme issue: The Cover "Non-Active" button is light, while the Active buttons are black. This should really be the other way around. Its non-intuitive to press the darker button.

**Comment by MCrissDev** [comment]
Hi, can you share a screenshot?

**Comment by thehaxxa** [comment]
![](https://i.imgur.com/lKaaQ95.jpg) The black buttons are pressible while white are inactive. This isn't consistent with the rest of the GUI.

**Comment by MCrissDev** [comment]
Please try with new version 1.3.2.5 and tell me if the issue is fixed
