### ISSUE TITLE
Ariela crashing

### ISSUE THREAD

**Issue by EduardoOliveira** [MCrissDev/Ariela#48]
Hi,
After the update ariela wouldn't open I had to reset the settings, now it crashes a while after I open it, the notification disappears until I open the app again. 

Thanks for the app.

**Comment by MCrissDev** [comment]
Hi,
Can you share Ariela logs? Thank you.

**Comment by EduardoOliveira** [comment]
Sorry for the delay.
There you go
https://gist.github.com/EduardoOliveira/b666b0d3d1dd6227e76d3fdf422068a6
the notification keeps closing from time to time.

Best Regards

**Comment by MCrissDev** [comment]
Thank you, i will check it out.

**Comment by MCrissDev** [comment]
Hi,
Can you also tell me Android version?

**Comment by EduardoOliveira** [comment]
Hi, I've attached a screen cap of the Os details 
https://photos.app.goo.gl/gDS2TJteunRKBL8p7

If you need any more information let me know

**Comment by MCrissDev** [comment]
Hello,
Sorry for long delay. Can you please check with this version if works: http://surodev.com/ariela/app-ariela-release.apk
Thank you.

**Comment by EduardoOliveira** [comment]
Running it now 😊
I don't know if it was the expected behaviour, but I had to uninstall the
playstore version and this version wiped my settings.

I'll get back to you wen I have some news

Thanks

**Comment by MCrissDev** [comment]
Great. Indeed you had to uninstall play store version because this version is not installed from play store. Once you confirm that this version is running fine i will update the play store version too.

**Comment by MCrissDev** [comment]
Hello,
Does the latest version of Ariela fixing this issue?

**Comment by EduardoOliveira** [comment]
Sorry for the delay,
Yes it still crashes, I've added another log to the gist.
https://gist.github.com/EduardoOliveira/b666b0d3d1dd6227e76d3fdf422068a6

**Comment by MCrissDev** [comment]
Please check with version 1.3.3.4 if the issue still present.

**Comment by MCrissDev** [comment]
Hello,
Is the issue still present in the latest version?

**Comment by EduardoOliveira** [comment]
Hi,
Running 1.3.4.0, so far so good

Thank you!
