### ISSUE TITLE
Lovelace Weather card does not work

### ISSUE THREAD

**Issue by Devqon** [MCrissDev/Ariela#5]
I have configured a weather card, which does not seem to work with Ariela:
![image](https://user-images.githubusercontent.com/9316480/52408271-d665b800-2ad2-11e9-9b4e-450d3451f346.png)

Lovelace configuration:
```
      - type: weather-forecast
        entity: weather.buienradar
```
Using the [buienradar platform](https://www.home-assistant.io/components/weather.buienradar/)

It does work in the home-assistant app:
![image](https://user-images.githubusercontent.com/9316480/52408344-057c2980-2ad3-11e9-82e0-8ae994d431db.png)

**Comment by MCrissDev** [comment]
Only dark sky component works at the moment. I will add support for this in short time.

**Comment by Devqon** [comment]
Awesome, I didn't think that the platform would matter. The dark sky does work indeed.

**Comment by MCrissDev** [comment]
Added support for weather lovelace card in version 1.2.9.7
