### ISSUE TITLE
SSID WiFi-based location

### ISSUE THREAD

**Issue by TASSDevon** [MCrissDev/Ariela#55]
Could use the connected WiFi SSID to determine a user's location, e.g. we already know and can configure what the home SSID is, could add several more (e.g. Work wifi, in-car wifi, ...)

**Comment by stsybizov** [comment]
Hey, You have two statuses, at home and not at home, as you want to use other networks.

**Comment by MCrissDev** [comment]
Hello @TASSDevon i think you want to automatically send a GPS location based on the network connected. Eg: send work GPS location when connected to home wifi?

**Comment by TASSDevon** [comment]
You could indeed trigger a GPS location update when connected to a certain SSID.

What I was thinking is that you define what the lat/lon is for several SSIDs in Home Assistant or Ariela, based on that it knows where you are

**Comment by Mace404** [comment]
I would like this feature too.
A list manageable in Ariela with SSID + GPS locations. When connected to a SSID, Ariela sends that GPS coordinates to Home Assistant.

GPS coordinates could be manual entry and/or detect current location and add/update to SSID.

**Comment by MCrissDev** [comment]
This feature already implemented by wifi & zones option
