### ISSUE TITLE
[Feature Request] MQTT Retain

### ISSUE THREAD

**Issue by stolenvw** [MCrissDev/Ariela#58]
Would like to see an option to enable the MQTT retain flag.  I use the phone next alarm and when restarting home assistant it shows as unknown till I either open Ariela or change my alarm so that the MQTT message is sent again.

**Comment by MCrissDev** [comment]
Thank you very much for the suggestion. I will see what i can do about this.

**Comment by MCrissDev** [comment]
Added this option in 1.3.3.6 version.
