### ISSUE TITLE
Alarm Sensor wrong time

### ISSUE THREAD

**Issue by MCrissDev** [MCrissDev/Ariela#59]
From user : "I use it on my Galaxy Phone. The Mqtt Sensor next Alarm Show me always alarm Time - 5 Minutes as State. On my other Phone the State of time from alarm is correct."
Phones used: Samsung S8+ , Android P, S10+

**Comment by stolenvw** [comment]
I have same issue on a Samsung S9

Also now after last update time is showing like 2019-6-11T03:30-0400

**Comment by pgodinic** [comment]
Any solution for this? 
Also my alarm sensor for most alarm time values sets alarm sensor state to 2019-10-04T07:30+0200 and for other time values it appears with -5 offset
@stolenvw you can create template sensor and parse it as you want. Example: 
      pgodinic_a50_alarm:
        friendly_name: "Alarm Petar"
        value_template: "{{ as_timestamp(states.sensor.pgodinic_a50_alarm_sensor.state) | timestamp_custom('%Y-%m-%d %H:%M:%S') }}"

**Comment by stolenvw** [comment]
@pgodinic  they way it shows doesn't bother me I changed my code that was using it to use it the way its shows now, it being off by 5min is little more annoying though

**Comment by MCrissDev** [comment]
Hello,
Ariela doesn't have any control regarding the time which is send to HA. Indeed Ariela will parse that time, but its value will not going to be changed. You may check your alarms to see if something its triggering the -5 minutes value.

**Comment by MCrissDev** [comment]
Closed, the alarm info its only set by remote apps.
