### ISSUE TITLE
Unregister Webhook

### ISSUE THREAD

**Issue by CAVACO-PT** [MCrissDev/Ariela#68]
Hello , thanks for you great app , i need some help , when i turn the mobile app sensors on my samsung s10 phone i get these errors in Home assistant 0.94.2 .. and it doesnt stop .... am i doing something wrong or do i need to add something to register them , with mqtt the sensors work fine .... 

Received message for unregistered webhook 6b9bbadc2f2161dc6dbe87577bf6e2a0f1aaf6f3c9ef623d6927a6c73fc9f596
6:32 PM components/webhook/__init__.py (WARNING)

thanks for the help

**Comment by CAVACO-PT** [comment]
Refusing to update non-registered sensor: e311511fdc33b09e662df16faab9909a7e302e434eea8e13dab9cf84f56c5b0a_mobile_app_XXX_battery
6:45 PM components/mobile_app/webhook.py (ERROR) - message first occured at 6:43 PM and shows up 18 times

**Comment by MCrissDev** [comment]
Hello,

Please try to re-register the device on mobile_app from Ariela -> Settings -> Force Mobile App and tell me if the issue persist.
Thank you.

**Comment by CAVACO-PT** [comment]
@MCrissDev  it keeps happening ... when i force the mobile app it creates in homeassistant another sensor , but the error messages keep happening in home assistant ... maybe a bug with new version 0.94.2 .....
Thanks for you great app ... already bought the pro version  keep it up

Received message for unregistered webhook bb2db4facb093662ad421741944ebe77ff565901051a2fd7400f3defa7a1ecf5
8:23 AM components/webhook/__init__.py (WARNING)

**Comment by MCrissDev** [comment]
Can you tell me which Ariela version you have please?

**Comment by CAVACO-PT** [comment]
Ariela Pro 
Version 1.3.3.7
Buildtime : 2019-06-10

**Comment by MCrissDev** [comment]
Please update with latest 1.3.4.0 and try again.

**Comment by CAVACO-PT** [comment]
@MCrissDev  i updated all the devices i have with ariela to the 1.3.4.0 , and the homeassistant had a new minor version as well the 0.94.3 ... and so far no message .... thanks for your help

**Comment by MCrissDev** [comment]
Glad to hear its working. Closing this issue
