### ISSUE TITLE
Device Tracker

### ISSUE THREAD

**Issue by stolenvw** [MCrissDev/Ariela#69]
It keeps on sending gps location info even with device tracker setting off.  The gps info it is sending is also wrong its sending latitude as longitude and longitude as latitude in doing so it puts me in Antarctica

on Version: 1.3.3.9

**Comment by MCrissDev** [comment]
Hello,
Please check this issue if reproducing using version 1.3.4.0
Thank you

**Comment by stolenvw** [comment]
That has seemed to fix the issue thank you.
