### ISSUE TITLE
Entities Cards don't render correct if they contain counter elements

### ISSUE THREAD

**Issue by dacmcbibs** [MCrissDev/Ariela#76]
I have 2 entities cards , one shows conversations with hangouts, the other is a list of counters , both show empty boxes in Ariela.  Sample card configuration:
 - entities:
          - counter.counter1
          - counter.counter2
          - counter.counter3
 - entities:
          - counter.total_coins
          - counter.mario_easter_egg
          - counter.showoff_coins
        title: 'Example Title'
        type: entities
        show_header_toggle: false

If enabled both the title and header toggle will render , none of the counters do

**Comment by MCrissDev** [comment]
Please check with new version 1.3.4.6 (which should be available for download in few hours) if this issue still reproduce.

**Comment by dacmcbibs** [comment]
Counters are working!  My Hangout chats now show the word conversations, but no other values.  I'll have to check my configuration to see what kind of element it is, but counters are good.
