### ISSUE TITLE
Support for Lovelace Markdown card

### ISSUE THREAD

**Issue by TASSDevon** [MCrissDev/Ariela#77]
For example:

`  - content: '[title](https://www.example.com)'

    type: markdown`

Ironically GitHub is parsing my example :-)

**Comment by MCrissDev** [comment]
Can you share please a screenshot of how Ariela its displaying the entity and how HA does? Thank you.

**Comment by TASSDevon** [comment]
![Screenshot_20190701-151908](https://user-images.githubusercontent.com/6917072/60439799-bcf51200-9c13-11e9-9fd0-4b7fe6062da7.png)

**Comment by MCrissDev** [comment]
For this i will need to add support for BBCode which is not that easy to do. Still in the future i will add suport for it.

**Comment by TASSDevon** [comment]
There is no rush :-)  I guess there should be a library for it you can use, e.g. https://github.com/noties/Markwon

**Comment by MCrissDev** [comment]
Please check with new version 1.3.4.7 if this issue still persist. Thank you.

**Comment by TASSDevon** [comment]
Works! 👍

**Comment by TASSDevon** [comment]
Hmm I was too fast, the markdown is rendering OK but I cannot click on a link, nothing happens.

**Comment by MCrissDev** [comment]
Thank you, i will check it out.

**Comment by MCrissDev** [comment]
Hi,
Please check with version 1.3.4.8 if the issue still present. Thank you

**Comment by TASSDevon** [comment]
Links are opening now, thanks!
