### ISSUE TITLE
Header toggle always visible

### ISSUE THREAD

**Issue by TASSDevon** [MCrissDev/Ariela#79]
Regardless if header toggle is set to true or false in an entities card, Ariela always shows it ~~when there are entities that can toggle~~. It would be more consistent if Ariela only displays it when this property is set to true

**Comment by MCrissDev** [comment]
Please check with new version 1.3.4.6 (which should be available for download in few hours) if this issue still reproduce.

**Comment by TASSDevon** [comment]
Fixed
