### ISSUE TITLE
Lock icon missing from Lock Entity Lovelace card

### ISSUE THREAD

**Issue by david81** [MCrissDev/Ariela#8]
Ariela Version 1.2.8.4

HA Web UI:

![screenshot_20190218-102505](https://user-images.githubusercontent.com/918769/52960866-adadb000-3367-11e9-9566-49526a73fdb4.png)

Ariela:

![screenshot_20190218-081640](https://user-images.githubusercontent.com/918769/52960688-56a7db00-3367-11e9-8fac-37c743824ecf.png)

**Comment by MCrissDev** [comment]
Thank you for reporting this issue. Can you by any chance upload the logs also? Thank you.

**Comment by MCrissDev** [comment]
Fixed in version 1.2.9.1
