### ISSUE TITLE
VPN access

### ISSUE THREAD

**Issue by martin3000** [MCrissDev/Ariela#82]
If I travel and make a VPN from my phone to my home router, Ariela cannot access home assistant. All other apps think that I'm at home because I'm in the home net. With Ariela, it does not work.

When I make the first time configuration, why does Ariela want the name of my wifi network?

**Comment by MCrissDev** [comment]
Hello Martin,
The WiFi network its used in order to detect when you are home or not. What you can do is redo the setup and put the IP address in both local & external. Still, i will take into account this and see what i can do to force the connection.

**Comment by MCrissDev** [comment]
Hello,
I added a new setting in Ariela -> Settings -> Server connection -> VPN mode
When that setting is enabled, the internal IP address is used for connection. Please check with version 1.3.4.8 if this issue is resolved. Thank you.

**Comment by martin3000** [comment]
I wonder why arila must know about VPN? if the phone is "at home" via VPN, the apps don't see this. for them it is the same as when I am at home.

**Comment by MCrissDev** [comment]
Ariela needs to determine the current connection type. If its over wifi and the wifi is the home one it will use the internal ip for connecting. If its over wifi and the wifi is not the home one, then the external ip is used for connecting. If the phone connection is over 3G / 4G etc, then the external ip is connected. 

When using VPN, Ariela detects a connection type, but is very possible the external ip to be used because it doens't know the a vpn connection is available, and if the external ip is not set, of course the connection will going to fail.

**Comment by martin3000** [comment]
And what if you just try the internal ip and if it not works, the external ip?
What you should fix: if the external ip is not configured in the app, and I try to connect, then try the internal ip, even if it is a 4G connection.

**Comment by MCrissDev** [comment]
"What you should fix: if the external ip is not configured in the app, and I try to connect, then try the internal ip, even if it is a 4G connection."
Yes, that is how its supposed to be done, but if i do like this i will have users that complain that Ariela tried to connect even if they didn't setup the external.

**Comment by martin3000** [comment]
Why should they complain? It is only a 10ms test?

**Comment by MCrissDev** [comment]
Well because when that test is done Ariela is sending over the network their credentials, meaning someone could steal that data.

**Comment by martin3000** [comment]
Ok I see the point. But you can test if the server is there by sending a ping or something like that. Just a test if the server can be reached.

**Comment by MCrissDev** [comment]
Hello,
A new option was added to Ariela - VPN detection. Meaning that if you have the older VPN setting active and you do not have a working VPN , older URL IP detection is used. 
Regarding the options you mentioned, i know about this and i will see what i can do about it.
