### ISSUE TITLE
Gauge card not taking name parameter into account

### ISSUE THREAD

**Issue by TASSDevon** [MCrissDev/Ariela#83]
The gauge card is using the entity's name rather than using the name field in the gauge card configuration.
E.g.:

  - entity: sensor.luftdata_temperature_dht22
    max: 35
    min: 0
    name: Temperatuur
    severity:
      green: 18
      red: 28
      yellow: 24
    type: gauge

So it would show ""luftdata_temperature_dht22" rather than "Temperatuur"

**Comment by MCrissDev** [comment]
I am not really sure i understand what you mean. Using this config Ariela should show "Temperatuur". Isn't?

**Comment by TASSDevon** [comment]
Exactly, though it is not doing that. Instead, it show the entity name.

Desired/Expected: temperatuur
Current behaviour: Luftdata_temperature_dht22

**Comment by MCrissDev** [comment]
Got it, thank you for explanation.

**Comment by MCrissDev** [comment]
Hi,
Please check with version 1.3.4.8 if the issue still present. Thank you

**Comment by TASSDevon** [comment]
Fixed!
