### ISSUE TITLE
When shopping list is at bottom of view the keyboard will not stay open

### ISSUE THREAD

**Issue by mchinery** [MCrissDev/Ariela#9]
I have the shopping list at the bottom of a view and when I try to add a new item the keyboard opens and then closes straight away.
Therefore, you can not add a new item to the shopping list as the keyboard does not stay open.

Attached is a video of the problem and also the logs

[ariela_logfile.log](https://github.com/MCrissDev/Ariela/files/2876883/ariela_logfile.log)

[2019_02_18_17_38_24.zip](https://github.com/MCrissDev/Ariela/files/2876910/2019_02_18_17_38_24.zip)

**Comment by MCrissDev** [comment]
Thank you, i will investigate the issue.

**Comment by MCrissDev** [comment]
This issue should be fixed in latest Ariela version
